name: Daily
run-name: Executing Daily Updation Jobs

on:
  schedule:
    - cron: '30 16 * * *' # 00:30 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        options:
          - 'BirthdayArtwork'
          - 'CharaRedirect'

env:
  PASSWORD: ${{ secrets.PASSWORD }}
  SSO_USER_ID: ${{ secrets.SSO_USER_ID }}
  SSO_TOKEN: ${{ secrets.SSO_TOKEN }}

jobs:
  BirthdayArtwork:
    if: |
      github.event.schedule == '30 16 * * *' || 
      github.event.inputs.task == 'BirthdayArtwork'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Run Script
        run: node src/BirthdayArtwork.js

  CharaRedirect:
    if: |
      github.event.schedule == '30 16 * * *' || 
      github.event.inputs.task == 'CharaRedirect'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Run Script
        run: node src/CharaRedirect.js
