name: GI

on:
  schedule:
    - cron: '5 4 * * *' # 12:05 CST
    - cron: '5 7 * * *' # 15:05 CST
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        options:
          - 'UpdateData'
          - 'BirthdayArtwork'
          - 'CharaInformation'
          - 'BirthdayMail'

jobs:
  UpdateData:
    if: |
      github.event.schedule == '5 4 * * *' ||
      github.event.inputs.task == 'UpdateData'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Run Script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node src/GI/UpdateData.js
      - name: Commit and Push
        run: |
          git config --global user.name Sparsle
          git config --global user.email ${{ secrets.EMAIL }}
          git add data/GI.json
          if git diff-index --quiet HEAD; then
            echo "No change."
          else
            git commit -m "Update GI.json automatically"
            git push
          fi

  BirthdayArtwork:
    if: |
      github.event.schedule == '5 4 * * *' ||
      github.event.inputs.task == 'BirthdayArtwork'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Set Timezone
        run: sudo timedatectl set-timezone Asia/Shanghai
      - name: Run Script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node src/GI/BirthdayArtwork.js

  CharaInformation:
    if: |
      github.event.schedule == '5 4 * * *' ||
      github.event.inputs.task == 'CharaInformation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node src/GI/CharaInformation.js
