name: MGP

on:
  schedule:
    - cron: '5 16 * * *' # 00:05 CST

jobs:
  Statistics:
    if: |
      github.event.schedule == '5 16 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - name: Run Script
        env:
          CONFIG: ${{ secrets.CONFIG }}
        run: node src/MGP/Statistics.js
      - name: Commit and Push
        run: |
          git config --global user.name Sparsle
          git config --global user.email ${{ secrets.EMAIL }}
          git add data/MGP.json
          if git diff-index --quiet HEAD; then
            echo "No change."
          else
            git commit -m "Update MGP.json automatically"
            git push
          fi
